spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suzhou?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  resources:
    static-locations: classpath:templates/,classpath:static/
mybatis:
  mapper-locations: classpath:mapper/*.xml